#!/bin/bash
# HLstatsX Community Edition - Real-time player and clan rankings and statistics
# Copyleft (L) 2008-20XX Nicholas Hastings (nshastings@gmail.com)
# http://www.hlxcommunity.com
#
# HLstatsX Community Edition is a continuation of 
# ELstatsNEO - Real-time player and clan rankings and statistics
# Copyleft (L) 2008-20XX Malte Bayer (steam@neo-soft.org)
# http://ovrsized.neo-soft.org/
# 
# ELstatsNEO is an very improved & enhanced - so called Ultra-Humongus Edition of HLstatsX
# HLstatsX - Real-time player and clan rankings and statistics for Half-Life 2
# http://www.hlstatsx.com/
# Copyright (C) 2005-2007 Tobias Oetzel (Tobi@hlstatsx.com)
#
# HLstatsX is an enhanced version of HLstats made by Simon Garner
# HLstats - Real-time player and clan rankings and statistics for Half-Life
# http://sourceforge.net/projects/hlstats/
# Copyright (C) 2001  Simon Garner
#             
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# For support and installation notes visit http://www.hlxcommunity.com



# set your correct HLstatsX perl path
perldir=/usr/local/games/hlstatsx/perl
cd ${perldir}

# check if you have a structure for hlstats in your homedir
# if you have it will try to read the conf from there, else use the default
# located in /usr/local/games/hlstatsx/perl/hlstats.conf

if [[ -d ~/hlstats && -r ~/hlstats/hlstats.conf ]];then
	confdir=~/hlstats
else
	confdir=${perldir}
fi

# verify that you have write access to the directories
if [ ! -w ${confdir} ]; then
	echo "you need write access to ${confdir}"
	exit 1
fi

# verify that you have a logs directory
if [ ! -d ${confdir}/logs ];then
	mkdir ${confdir}/logs
fi

if [ ! -w ${confdir}/logs ];then
	echo "you need write access to ${confdir}/logs"
	exit 1
fi

case "$1" in
   start)
       echo "Starting HLstatsX...";
       if [ -f ${confdir}/hlstats.pid ]; then
          kill -0 `cat ${confdir}/hlstats.pid` >/dev/null 2>&1
          if [ "$?" == "0" ]; then
              echo "HLstatsX already running!"
          else
              rm -rf ${confdir}/hlstats.pid
              ./hlstats.pl --configfile=${confdir}/hlstats.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
              echo $! >${confdir}/hlstats.pid
              echo "PID file created"
              echo "Started successfully"
          fi
       else
          ./hlstats.pl --configfile=${confdir}/hlstats.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
          echo $! >${confdir}/hlstats.pid
          echo "PID file created"
          echo "Started successfully"
       fi
     ;;
   stop)
       echo "Stopping HLstatsX..."
       kill -9 `cat ${confdir}/hlstats.pid` >/dev/null 2>&1
       if [ "$?" == "0" ]; then
          rm -rf ${confdir}/hlstats.pid
          echo "Stopped successfully"
       else
          echo "No HLstatsX running!"
       fi
     ;;
   restart)
       echo "Restarting HLstatsX..."
       kill -9 `cat ${confdir}/hlstats.pid` >/dev/null 2>&1
       if [ "$?" == "0" ]; then
           rm -rf ${confdir}/hlstats.pid
           ./hlstats.pl --configfile=${confdir}/hlstats.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
           echo $! >${confdir}/hlstats.pid
           echo "PID file created"
           echo "Restarted successfully"
       else    
           echo "HLstatsX"
           if [ -f ${confdir}/hlstats.pid ]; then
             rm -rf ${confdir}/hlstats.pid
           fi
           ./hlstats.pl --configfile=${confdir}/hlstats.conf >${confdir}/logs/log`date +_%Y%m%d_%H-%M-%S` 2>&1 &
           echo $! >${confdir}/hlstats.pid
           echo "PID file created"
           echo "Started successfully"
       fi
     ;;
   *)
       echo "Usage: ./run_hlstats [ start | stop | restart ]"
     ;;
esac

#
exit 0
