INSERT IGNORE INTO `hlstats_Weapons` (`game`, `code`, `name`, `modifier`) VALUES
('l4d2', 'rifle', 'M16 Assault Rifle', 1.00),
('l4d2', 'autoshotgun', 'Auto Shotgun', 1.00),
('l4d2', 'pumpshotgun', 'Pump Shotgun', 1.30),
('l4d2', 'smg', 'Uzi', 1.20),
('l4d2', 'dual_pistols', 'Dual Pistols', 1.60),
('l4d2', 'pipe_bomb', 'Pipe Bomb', 1.00),
('l4d2', 'hunting_rifle', 'Hunting Rifle', 1.00),
('l4d2', 'pistol', 'Pistol', 2.00),
('l4d2', 'prop_minigun', 'Mounted Machine Gun', 1.20),
('l4d2', 'tank_claw', 'Tank''s Claws', 2.00),
('l4d2', 'hunter_claw', 'Hunter''s Claws', 3.00),
('l4d2', 'smoker_claw', 'Smoker''s Claws', 3.00),
('l4d2', 'boomer_claw', 'Boomer''s Claws', 3.00),
('l4d2', 'jockey_claw', 'Jockey''s Claws', 3.00),
('l4d2', 'spitter_claw', 'Spitter''s Claws', 3.00),
('l4d2', 'charger_claw', 'Charger''s Claws', 3.00),
('l4d2', 'inferno', 'Molotov/Gas Can Fire', 1.20),
('l4d2', 'infected', 'Infected Horde', 1.00),
('l4d2', 'witch', 'Witch''s Claws', 1.00),
('l4d2', 'entityflame', 'Blaze', 3),
('l4d2', 'first_aid_kit', 'First Aid Kit Smash', 1.5),
('l4d2', 'gascan', 'Gas Can Smash', 1.5),
('l4d2', 'molotov', 'Molotov Smash', 1.5),
('l4d2', 'pain_pills', 'Pain Pills Smash', 1.5),
('l4d2', 'player', 'Player', 1),
('l4d2', 'propanetank', 'Propane Tank Smash', 1.5),
('l4d2', 'tank_rock', 'Tank''s Rock', 1.5),
('l4d2', 'oxygentank', 'Oxygen Tank Smash', 1.5),
('l4d2', 'prop_physics', 'Prop Physics', 1),
('l4d2', 'defibrillator', 'Defibrillator', 1.5),
('l4d2', 'grenade_launcher', 'Grenade Launcher', 1),
('l4d2', 'pistol_magnum', 'Magnum', 1),
('l4d2', 'rifle_ak47', 'AK-47', 1),
('l4d2', 'rifle_desert', 'Combat Rifle', 1),
('l4d2', 'shotgun_chrome', 'Chrome Shotgun', 1),
('l4d2', 'shotgun_spas', 'Combat Shotgun', 1),
('l4d2', 'smg_silenced', 'Uzi (silenced)', 1),
('l4d2', 'sniper_military', 'Sniper Rifle', 1),
('l4d2', 'vomitjar', 'Vomit Jar Smash', 1.5),
('l4d2', 'baseball_bat', 'Baseball Bat', 1.5),
('l4d2', 'cricket_bat', 'Cricket Bat', 1.5),
('l4d2', 'crowbar', 'Crowbar', 1.5),
('l4d2', 'electric_guitar', 'Electric Guitar', 1.5),
('l4d2', 'fireaxe', 'Fireaxe', 1.5),
('l4d2', 'frying_pan', 'Frying Pan', 1.5),
('l4d2', 'katana', 'Katana', 1.5),
('l4d2', 'knife', 'Knife', 1.5),
('l4d2', 'machete', 'Machete', 1.5),
('l4d2', 'tonfa', 'Tonfa', 1.5);

INSERT IGNORE INTO `hlstats_Weapons` (`game`, `code`, `name`, `modifier`)
(SELECT code, 'tf_pumpkin_bomb', 'Pumpkin Bomb', 2 FROM hlstats_Games WHERE `realgame` = 'tf');

INSERT IGNORE INTO `hlstats_Awards` (`awardType`, `game`, `code`, `name`, `verb`)
(SELECT 'W',code,'tf_pumpkin_bomb', 'Pumpkin Bomber', 'kills by pumpkin bomb' FROM hlstats_Games WHERE `realgame` = 'tf');