INSERT IGNORE INTO `hlstats_Actions` (`game`, `code`, `reward_player`, `reward_team`, `team`, `description`, `for_PlayerActions`, `for_PlayerPlayerActions`, `for_TeamActions`, `for_WorldActions`) VALUES
('l4d2', 'headshot', 0, 0, '', 'Headshot Kill', '1', '', '', ''),
('l4d2', 'killed_gas', 1, 0, '', 'Killed a Smoker', '1', '0', '0', '0'),
('l4d2', 'killed_exploding', 1, 0, '', 'Killed a Boomer', '1', '0', '0', '0'),
('l4d2', 'killed_hunter', 1, 0, '', 'Killed a Hunter', '1', '0', '0', '0'),
('l4d2', 'killed_tank', 3, 0, '', 'Killed a Tank', '1', '0', '0', '0'),
('l4d2', 'killed_witch', 3, 0, '', 'Killed a Witch', '1', '0', '0', '0'),
('l4d2', 'killed_spitter', 3, 0, '', 'Killed a Spitter', '1', '0', '0', '0'),
('l4d2', 'killed_jockey', 3, 0, '', 'Killed a Jockey', '1', '0', '0', '0'),
('l4d2', 'killed_charger', 3, 0, '', 'Killed a Charger', '1', '0', '0', '0'),
('l4d2', 'killed_survivor', 25, 0, '', 'Incapacitated/Killed Survivor', '0', '1', '0', '0'),
('l4d2', 'tongue_grab', 6, 0, '', '(Smoker) Tongue Grabbed Survivor', '0', '1', '0', '0');

INSERT IGNORE INTO `hlstats_Awards` (`awardType`, `game`, `code`, `name`, `verb`) VALUES
('O', 'l4d2', 'headshot', 'Brain Salad', 'headshot kills'),
('O', 'l4d2', 'killed_exploding', 'Stomach Upset', 'killed Boomers'),
('O', 'l4d2', 'killed_gas', 'No Smoking Section', 'killed Smokers'),
('O', 'l4d2', 'killed_hunter', 'Hunter Punter', 'killed Hunters'),
('O', 'l4d2', 'killed_spitter', 'Spittle Splatter', 'Spitters Splated'),
('O', 'l4d2', 'killed_charger', 'Bumrush Thwarter', 'killed Chargers'),
('O', 'l4d2', 'killed_jockey', 'Hunter Punter', 'killed Jockeys'),
('P', 'l4d2', 'killed_survivor', 'Dead Wreckening', 'downed Survivors'),
('O', 'l4d2', 'killed_tank', 'Tankbuster', 'killed Tanks'),
('O', 'l4d2', 'killed_witch', 'Inquisitor', 'killed Witches'),
('P', 'l4d2', 'tongue_grab', 'Drag &amp; Drop', 'constricted Survivors');

INSERT IGNORE INTO `hlstats_Games` (`code`, `name`, `realgame`, `hidden`) VALUES
('l4d2', 'Left 4 Dead 2', 'l4d', '1');

INSERT IGNORE INTO `hlstats_Roles` (`game`, `code`, `name`, `hidden`) VALUES
('l4d2', 'Producer', 'Rochelle', '0'),
('l4d2', 'Mechanic', 'Ellis', '0'),
('l4d2', 'Coach', 'Coach', '0'),
('l4d2', 'Gambler', 'Nick', '0'),
('l4d2', 'GAS', 'Smoker', '0'),
('l4d2', 'EXPLODING', 'Boomer', '0'),
('l4d2', 'HUNTER', 'Hunter', '0'),
('l4d2', 'TANK', 'Tank', '0'),
('l4d2', 'CHARGER', 'Charger', '0'),
('l4d2', 'SPITTER', 'Spitter', '0'),
('l4d2', 'JOCKEY', 'Jockey', '0'),
('l4d2', 'infected', 'Infected Horde', '0'),
('l4d2', 'witch', 'Witch', '0');

INSERT IGNORE INTO `hlstats_Teams` (`game`, `code`, `name`, `hidden`, `playerlist_bgcolor`, `playerlist_color`, `playerlist_index`) VALUES
('l4d2', 'Survivor', 'Survivors', '0', '#E0E4E5', '#4B6168', 1),
('l4d2', 'Infected', 'Infected', '0', '#E5D5D5', '#68090B', 2);

INSERT IGNORE INTO `hlstats_Weapons` (`game`, `code`, `name`, `modifier`) VALUES
('l4d2', 'rifle', 'M16 Assault Rifle', 1.00),
('l4d2', 'autoshotgun', 'Auto Shotgun', 1.00),
('l4d2', 'pumpshotgun', 'Pump Shotgun', 1.30),
('l4d2', 'smg', 'Uzi', 1.20),
('l4d2', 'dual_pistols', 'Dual Pistols', 1.60),
('l4d2', 'pipe_bomb', 'Pipe Bomb', 1.00),
('l4d2', 'hunting_rifle', 'Hunting Rifle', 1.00),
('l4d2', 'pistol', 'Pistol', 2.00),
('l4d2', 'prop_minigun', 'Mounted Machine Gun', 1.20),
('l4d2', 'tank_claw', 'Tank''s Claws', 2.00),
('l4d2', 'hunter_claw', 'Hunter''s Claws', 3.00),
('l4d2', 'smoker_claw', 'Smoker''s Claws', 3.00),
('l4d2', 'boomer_claw', 'Boomer''s Claws', 3.00),
('l4d2', 'jockey_claw', 'Jockey''s Claws', 3.00),
('l4d2', 'spitter_claw', 'Spitter''s Claws', 3.00),
('l4d2', 'charger_claw', 'Charger''s Claws', 3.00),
('l4d2', 'inferno', 'Molotov/Gas Can Fire', 1.20),
('l4d2', 'infected', 'Infected Horde', 1.00),
('l4d2', 'witch', 'Witch''s Claws', 1.00),
('l4d2', 'entityflame', 'Blaze', 3),
('l4d2', 'first_aid_kit', 'First Aid Kit Smash', 1.5),
('l4d2', 'gascan', 'Gas Can Smash', 1.5),
('l4d2', 'molotov', 'Molotov Smash', 1.5),
('l4d2', 'pain_pills', 'Pain Pills Smash', 1.5),
('l4d2', 'player', 'Player', 1),
('l4d2', 'propanetank', 'Propane Tank Smash', 1.5),
('l4d2', 'tank_rock', 'Tank''s Rock', 1.5),
('l4d2', 'oxygentank', 'Oxygen Tank Smash', 1.5),
('l4d2', 'prop_physics', 'Prop Physics', 1),
('l4d2', 'defibrillator', 'Defibrillator', 1.5),
('l4d2', 'grenade_launcher', 'Grenade Launcher', 1),
('l4d2', 'pistol_magnum', 'Magnum', 1),
('l4d2', 'rifle_ak47', 'AK-47', 1),
('l4d2', 'rifle_desert', 'Combat Rifle', 1),
('l4d2', 'shotgun_chrome', 'Chrome Shotgun', 1),
('l4d2', 'shotgun_spas', 'Combat Shotgun', 1),
('l4d2', 'smg_silenced', 'Uzi (silenced)', 1),
('l4d2', 'sniper_military', 'Sniper Rifle', 1),
('l4d2', 'vomitjar', 'Vomit Jar Smash', 1.5),
('l4d2', 'baseball_bat', 'Baseball Bat', 1.5),
('l4d2', 'cricket_bat', 'Cricket Bat', 1.5),
('l4d2', 'crowbar', 'Crowbar', 1.5),
('l4d2', 'electric_guitar', 'Electric Guitar', 1.5),
('l4d2', 'fireaxe', 'Fireaxe', 1.5),
('l4d2', 'frying_pan', 'Frying Pan', 1.5),
('l4d2', 'katana', 'Katana', 1.5),
('l4d2', 'knife', 'Knife', 1.5),
('l4d2', 'machete', 'Machete', 1.5),
('l4d2', 'tonfa', 'Tonfa', 1.5);

